# Git pre-commit hooks config file
# Only takes effect if you have pre-commit installed in the env,
# and after you run `pre-commit install`
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Out-of-the-box hooks from the pre-commit org
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files

  # Code formatting with black
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # Run black on Python code blocks in documentation files
  -   repo: https://github.com/asottile/blacken-docs
      rev: 1.19.1
      hooks:
      -   id: blacken-docs
          additional_dependencies: [black==24.10.0]
          args: [--skip-errors]
