[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
branch = true
source = ["moacean_parcels", "tests"]

[tool.coverage.report]
show_missing = true
