# conda environment description file for readthedocs build environment

name: moacean-parcels-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.9

  # readthedocs packages
  - mock
  - pillow
  - pip
  - sphinx
  - sphinx_rtd_theme
  - pip:
      - recommonmark
      - readthedocs-sphinx-ext
