# conda environment description file for readthedocs build environment

name: moacean-parcels-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - bottleneck
  - cartopy
  - cmocean
  - ffmpeg
  - ipython
  - jupyterlab
  - nbsphinx
  - parcels
  - pip
  - pytest
  - python=3.10

  # Sphinx and extensions
  - nbsphinx==0.9.5
  - sphinx==8.1.3
  - sphinx-notfound-page==1.0.4
  - sphinx-rtd-theme==3.0.0

  # readthedocs build system packages
  - mock
  - pillow
  - pip:
    - commonmark
    - recommonmark
    - readthedocs-sphinx-ext

    # install MoaceanParcels package
    - ../
