# conda environment description file for readthedocs build environment

name: moacean-parcels-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - bottleneck
  - cartopy
  - cmocean
  - ffmpeg
  - ipython
  - jupyterlab
  - nbsphinx
  - parcels
  - pip
  - pytest
  - python=3.10

  # readthedocs packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
  - sphinx-notfound-page

  - pip:
    - recommonmark
    - readthedocs-sphinx-ext

    # install MoaceanParcels package
    - ../
