# conda environment description file for readthedocs build environment

name: moacean-parcels-rtd

channels:
  - conda-forge
  - nodefaults

dependencies:
  - ipython
  - nbsphinx
  - python=3.10

  # readthedocs packages
  - mock
  - pillow
  - pip
  - sphinx
  - sphinx_rtd_theme
  - sphinx-notfound-page
  - pip:
    - recommonmark
    - readthedocs-sphinx-ext

    # install MoaceanParcels package
    - ../
